todoproject/config/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('todoapp/', include('todoapp.urls')),
    path('admin/', admin.site.urls),
]

todoproject/todoapp/urls.py
from django.urls import path
from . import views

app_name = 'todoapp'

urlpatterns = [
    path('list/', views.TodoListView.as_view(), name='list'),
    path('detail/<int:pk>/', views.TodoDetailView.as_view(), name='detail'),
    path('create/', views.TodoCreateView.as_view(), name='create'),
    path('update/<int:pk>/', views.TodoUpdateView.as_view(), name='update'),
    path('delete/<int:pk>/', views.TodoDeleteView.as_view(), name='delete'),
]

todoproject/todoapp/models.py
from django.db import models


class Todo(models.Model):
    todo = models.CharField('ToDo', max_length=100, blank=False)
    created_at = models.DateTimeField('作成日時', auto_now_add=True)
    updated_at = models.DateTimeField('更新日時',auto_now=True)


    class Meta:
        ordering = ['id']

    def __str__(self):
        return self.todo
    
# Create your models here.











































































todoproject/todoapp/forms.py
from django import forms
from .models import Todo

class TodoForm(forms.ModelForm):
    class Meta:
        model = Todo
        exclude = ('created_at', 'updated_at',)
        

todoproject/todoapp/views.py
from django.views import generic
from django.urls import reverse_lazy
from .models import Todo
from .forms import TodoForm

class TodoListView(generic.ListView):
    model = Todo
    paginate_by = 5

class TodoDetailView(generic.DetailView):
    model = Todo

class TodoCreateView(generic.CreateView):
    model = Todo
    form_class = TodoForm
    success_url = reverse_lazy('todoapp:list')

class TodoUpdateView(generic.UpdateView):
    model = Todo
    form_class = TodoForm
    success_url = reverse_lazy('todoapp:list')

class TodoDeleteView(generic.DeleteView):
    model = Todo
    success_url = reverse_lazy('todoapp:list')
    


# Create your views here.

todoproject/todoapp/templates/base.html
{% load static %}

<html lang="ja">
<head>
    <meta charset="utf-8">
</head>
<body>
    {% block content %}
    {% endblock %}
</body>
</html>

todoproject/todoapp/templates/todoapp/todo_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
<h1>ToDoの削除</h1>
<table>
    <tr>
        <th>ID</th>
        <td>{{ object.id }}</td>
    </tr>
    <tr>
        <th>ToDo</th>
        <td>{{ object.todo }}</td>
    </tr>
    <tr>
        <th>作成日時</th>
        <td>{{ object.created_at }}</td>
    </tr>
    <tr>
        <th>更新日時</th>
        <td>{{ object.updated_at }}</td>
    </tr>
</table>
<form action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <input type="submit"value="削除" />
</form>
<a href="{% url 'todoapp:list' %}">戻る</a>

{% endblock %}

todoproject/todoapp/templates/todoapp/todo_detail.html
{% extends 'base.html' %}

{% block content %}
<h1>ToDoの詳細</h1>
<table>
    <tr>
        <th>ID</th>
        <td>{{ object.id }}</td>
    </tr>
    <tr>
        <th>ToDo</th>
        <td>{{ object.todo }}</td>
    </tr>
    <tr>
        <th>作成日時</th>
        <td>{{ object.created_at }}</td>
    </tr>
    <tr>
        <th>更新日時</th>
        <td>{{ object.updated_at }}</td>
    </tr>
</table>
<a href="{% url 'todoapp:list' %}">見る</a>
{%endblock%}

todoproject/todoapp/templates/todoapp/todo_form.html
{% extends 'base.html' %}

{% block content %}

{% if object %}
<h1>ToDoの編集</h1>
{% else %}
<h1>Todoの作成</h1>
{% endif %}


<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form }}
    <button type="submit">送信</button>
</form>
<a href="{% url 'todoapp:list' %}">戻る</a>
{%endblock%}

todoproject/todoapp/templates/todoapp/todo_list.html
{% extends 'base.html' %}

{% block content %}
<h1>ToDoの一覧</h1>
<a href="{% url 'todoapp:create' %}">追加</a>
<table>
    <thead>
        <tr>
            <th scope="col">ID</th>
            <th scope="col">ToDo</th>
            <th scope="col">作成日時</th>
            <th scope="col">更新日時</th>
            <th scope="col">創作</th>
        </tr>
    </thead>
    <tbody>
        {% for item in object_list %}
        <tr>
            <td scope="row"><a href="{% url 'todoapp:detail' pk=item.id %}">{{ item.id }}</a></td>
            <td>{{ item.todo }}</td>
            <td>{{ item.created_at }}</td>
            <td>{{ item.updated_at }}</td>
            <td>
                <a href="{% url 'todoapp:update' pk=item.id %}">修正</a>
                <a href="{% url 'todoapp:delete' pk=item.id %}">削除</a>
            </td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock %}
